services:
  duoclone-backend:
    ports:
      - "8080:8080"
    build: .
    container_name: duoclone-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      AUTH_COOKIE_DOMAIN: ${AUTH_COOKIE_DOMAIN}
      AUTH_COOKIE_SAME_SITE: ${AUTH_COOKIE_SAME_SITE}
      AUTH_COOKIE_SECURE: ${AUTH_COOKIE_SECURE}
      FRONTEND_ORIGINS: ${FRONTEND_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: unless-stopped