services:
  postgres:
    image: postgres:17
    container_name: duoclone-postgres
    environment:
      POSTGRES_DB: "${SPRING_DATASOURCE_DB_NAME}"
      POSTGRES_USER: "${SPRING_DATASOURCE_USERNAME}"
      POSTGRES_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  pgdata: