services:
  mysql:
    image: mysql:8.4
    container_name: duoclone-mysql
    environment:
      MYSQL_DATABASE: "${SPRING_DATASOURCE_DB_NAME}"
      MYSQL_USER: "${SPRING_DATASOURCE_USERNAME}"
      MYSQL_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysqldata: